### ISSUE TITLE
1.1 Greška pri pozivu metode za registrovanje novog korisnika

### ISSUE THREAD

**Issue by amarsatara** [SoftverInzenjeringETFSA/SI2016_TIM13#2]
Pri pozivanju metode za registrovanje novog korisnika - isti se nije mogao registrovati zato što se javila greška pri pokušaju dodavanja novog rekorda kod kojeg je šifra bila null, iako smo je poslali u tijelo put zahtjeva.
Nakon što smo stavili da šifra može biti null zahtjev je uspješno prošao, očigledno je greška prilikom inicjalizacija objekta korisnici.

Testirana komponenta je korisnikKontroler.java
![image](https://cloud.githubusercontent.com/assets/22985287/26761162/dcfb4cec-492a-11e7-9690-5878954f4c72.png)

![image](https://cloud.githubusercontent.com/assets/22985287/26761176/f712b64c-492a-11e7-84de-978cf0ffaaae.png)

**Comment by osokolovic1** [comment]
popravljeno
