### ISSUE TITLE
1.2 Greška pri pozivanju metode za ažuriranje korisnika

### ISSUE THREAD

**Issue by amarsatara** [SoftverInzenjeringETFSA/SI2016_TIM13#3]
Pri pozivanju metode za ažuriranje korisnika, isti se nije mogao ažurirati zato što se pojavila greška te se ažuriranje nije moglo izvršiti.

Testirana komponenta je korisnikKontroler.java
![image](https://cloud.githubusercontent.com/assets/22985287/26761185/19d0f4e6-492b-11e7-83f2-c2402ba19e65.png)

**Comment by osokolovic1** [comment]
popravljeno
