### ISSUE TITLE
Nemogucnost kompajliranja backenda

### ISSUE THREAD

**Issue by goldlil** [SoftverInzenjeringETFSA/SI2016_TIM13#31]
Backend verziju koja je bila na githubu nije bilo moguce kompajlirati da bi se uopce moglo pristupiti testiranju. 

Greške su bile korištena je metoda addKorisnika koja je bila nepostojeća, da bi se projekat uopce mogao kompajlirati koristena je metoda registerKorisnika umjesto gore postojece. 

Korišten je tip blob u klasi fotografija, isti je morao biti zamjenjen sa tipm byte[] da jer je padala konekcija na bazu zbog toga.

**Comment by osokolovic1** [comment]
popravljeno
