### ISSUE TITLE
1.4 Greška pri pozivu metode za dodavanje korisnika

### ISSUE THREAD

**Issue by amarsatara** [SoftverInzenjeringETFSA/SI2016_TIM13#4]
Pri pozivanju metode za dodavanje korisnika dobivamo grešku. Razlog je pozivanje iste metode klase KorisnikService koja je pravila problem u testu „1.2“.

Testirana komponenta je korisnikKontroler.java
![image](https://cloud.githubusercontent.com/assets/22985287/26761191/4233ba54-492b-11e7-8230-ead505e37c1c.png)

**Comment by osokolovic1** [comment]
popravljeno
