### ISSUE TITLE
1.5 Greška pri pokušaju brisanja zapisa iz tabele.

### ISSUE THREAD

**Issue by amarsatara** [SoftverInzenjeringETFSA/SI2016_TIM13#5]
1.5 Nakon više pokušaja brisanja zapisa iz tabele, svaki put smo dobili istu grešku.

Testirana komponenta je korisnikKontroler.java
![image](https://cloud.githubusercontent.com/assets/22985287/26761198/6757f9bc-492b-11e7-8174-77921578cd4a.png)

**Comment by osokolovic1** [comment]
popravljeno
