### ISSUE TITLE
2.1 Frontend se ne pokreće na localhost-u na kojem bi trebao

### ISSUE THREAD

**Issue by amarsatara** [SoftverInzenjeringETFSA/SI2016_TIM13#7]
2.1 Frontend se ne pokreće na localhost-u na kojem bi trebao, već je potrebno dodati rutu /home.
![image](https://cloud.githubusercontent.com/assets/22985287/26761392/6b219e9c-492e-11e7-9200-ed6ffc4e7e97.png)

![image](https://cloud.githubusercontent.com/assets/22985287/26761398/83ac3706-492e-11e7-933e-ab6ea112741d.png)

**Comment by osokolovic1** [comment]
popravljeno
